### ISSUE TITLE
vimrc CTRL-P not working

### ISSUE THREAD

**Issue by tuxflo** [voku/dotfiles#10]
Hey! I'm using your .vimrc file and just tried to test the Ctrl-P plugin but if I hit <C>p there is a message that the command ag is missing:
` zsh:1: command not found: ag`
I'm running arch linux and cannot find a package containing the ag command.

**Comment by DrVanScott** [comment]
It's in package silversearcher-ag

**Comment by voku** [comment]
"silversearcher-ag": ag === Like grep or ack, but faster.

... so I close it!?
