### ISSUE TITLE
composure.sh replaced by an older version

### ISSUE THREAD

**Issue by DrVanScott** [voku/dotfiles#13]
Hi,

with commit 70cf939fb5143dcaed4ceae0b97c969fe347fe66 you introduced an older version of composure.sh:

Before it was something around: https://github.com/erichs/composure/tree/5c8e9af5ced028810e68a3c057afa59220eb0b8e
Your last version of this file is here: https://github.com/voku/dotfiles/blob/f7693a6bb542409c9a9e6ff76f4354e96d238ef9/.redpill/lib/composure.sh

Now it is something around: https://github.com/erichs/composure/tree/6927bbec42af114ef6fbdb9b955cb0d209293d21
Your version is here: https://github.com/voku/dotfiles/blob/70cf939fb5143dcaed4ceae0b97c969fe347fe66/.redpill/lib/composure.bash

Are there any reasons or just an accident?

**Comment by voku** [comment]
... just an copy&past accident and now I have added v1.3 -> https://github.com/voku/dotfiles/blob/master/.redpill/lib/composure.bash
