### ISSUE TITLE
Revert ff98806 ?

### ISSUE THREAD

**Issue by DrVanScott** [voku/dotfiles#29]
Maybe the change introduced by ff98806 should be reverted.

If you are in input mode, pressing ESC and a command may not lead to the desired result. For example: 

    Enter some text with several "the" (the the the)
    (while in normal mode)
    gg0
    /the
    a
    ^[
    n

In words: search for "the", enter input mode (append). Now hit ESC and - as soon as possible - 'n' to search for the next "the". Instead of jumping to the next match, a strange character is appended.

Another example:
(Make sure, ^[ is ESC, a single character)

    :let @a='a^[aexam^[aple^['
    @a

This should lead to 

    example

but instead generates

    áexamáple

Maybe better try to avoid mappings with META at all?

**Comment by voku** [comment]
Thx for the pull request, merged!
